common: &common
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  username: gklinsing
  pool: 5

development:
  <<: *common
  host: localhost
  database: r2d2_development

test:
  <<: *common
  database: r2d2_test

production:
  <<: *common
